### ISSUE TITLE
Handling inf while computing shortest paths

### ISSUE THREAD

**Issue by neurothew** [rkdan/small_world_propensity#91]
Hi Ryan, thank you very much for porting the small world propensity (SWP) from MATLAB to Python, it saves us a lot of time!

While I am computing SWP from thresholded network (thresholding by preserve `x%` strongest weights), sometimes I found strange behaviours in which the SWP would suddenly jump from a low value to a high value (see the figure below):

![image](https://github.com/rkdan/small_world_propensity/assets/24700304/169d7954-fbf9-442a-8eca-e6310b3985de)

After looking into the computation, I found that this is caused by the `inf` shortest path, since some nodes are not connected with any other nodes after thresholding. 

I then look into how this situation is handled in the toolbox, and I find in line 122 of `small_world_propensity.py`:
```    
if np.isinf(L_W) or np.isinf(L_reg) or np.isinf(L_rand):
        diff_path = 1
```

However, as I looked into the original implementation, I found that they actually handled it differently (see line 161-167,  https://kk1995.github.io/BauerLab/BauerLab/MATLAB/lib/+mouse/+graph/smallWorldPropensity.html#_sub2). In their implementation, when a node is disconnected from the system, they replace the `inf` with 0.

This can be easily replicated by adding one line inside `get_average_paths`:

```
def get_average_paths_updated(W: np.ndarray) -> float:
    """Get the average path length of a network.

    Args:
        W (np.ndarray): Adjacency matrix of the network.

    Returns:
        float: Average path length of the network.
    """
    path_matrix = csgraph.shortest_path(1/W, directed=False, unweighted=False)
    path_matrix[np.isinf(path_matrix)] = 0 # <---------------------------------------------the added line
    L_W = np.triu(path_matrix).sum() / (len(W) * (len(W) - 1) / 2)

    return L_W

```

After doing so, my plot would become:
![image](https://github.com/rkdan/small_world_propensity/assets/24700304/e43a889e-eb69-4130-a77e-5eaa783528e2)

It seems to make more sense than seeing a sudden surge in SWP.

Since I am not really an expert in network analysis, I wonder if such a fix is reasonable and would it be valid to make a pull request for it? Thanks!

**Comment by rkdan** [comment]
Hi @neurothew! Firstly, thanks for using the package, I hope it can be useful to you. And secondly, thanks for bringing this to my attention. I think you are right in that the current version is incorrectly handling the infinite cases of shortest paths.

I've made the necessary changes, so please let me know if that works. Apologies if you wanted to submit the PR yourself - I had to add some additional test cases to satisfy myself that it was working as intended and that behaviour was not too different from known networks.

**Comment by neurothew** [comment]
> Hi @neurothew! Firstly, thanks for using the package, I hope it can be useful to you. And secondly, thanks for bringing this to my attention. I think you are right in that the current version is incorrectly handling the infinite cases of shortest paths.
> 
> I've made the necessary changes, so please let me know if that works. Apologies if you wanted to submit the PR yourself - I had to add some additional test cases to satisfy myself that it was working as intended and that behaviour was not too different from known networks.

@rkdan Hi Ryan, thanks so much for addressing it so quickly! There's certainly no problem and no need for apologies : ) I am glad that I helped.
